### ISSUE TITLE
loginのredirectのtestうまくいかない

### ISSUE THREAD

**Issue by YukiY727** [YukiY727/Twitter_clone#5]
#4 でtestを作成していのですが、
```
Traceback (most recent call last):
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\ttter\accounts\tests.py", line 206, in test_success_post
    self.assertRedirects(response_post, reverse('base:top'))
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\testcases.py", line 351, in assertRedirects
    self.assertEqual(
AssertionError: 200 != 302 : Response didn't redirect as expected: Response code was 200 (expected 302)
```
というエラーが出てしまい、うまくtestが作れません。
解決策教えてほしいです！

**Comment by Akinori13** [comment]
`User.objects.create_user()`でユーザーを作成してください！少し挙動が異なるはずです。（`user.active=True`にならない）
ログインできていない場合は200が返される場合があるので、上記をまずは確認してください！

**Comment by YukiY727** [comment]
返信ありがとうございます！
User.objects.create_user()でuserを作るようにしたのですが、
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
............<django.db.models.query_utils.DeferredAttribute object at 0x0000025B5EFDE5B0>
.<django.db.models.query_utils.DeferredAttribute object at 0x0000025B5EFDE5B0>
F
======================================================================
FAIL: test_success_post (accounts.tests.TestLoginView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\ttter\accounts\tests.py", line 209, in test_success_post
    self.assertRedirects(response_post, reverse('base:top'))
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\testcases.py", line 351, in assertRedirects
    self.assertEqual(
AssertionError: 200 != 302 : Response didn't redirect as expected: Response code was 200 (expected 302)
```
変わらずエラーが出てしまいます。

**Comment by YukiY727** [comment]
どこが原因なのでしょうか？
助けてもらえると嬉しいです！

**Comment by Akinori13** [comment]
`print(response_post.context["form"])`でエラー内容を確認してください！

**Comment by YukiY727** [comment]
返信ありがとうございます！
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.............<tr>
    <td colspan="2">
      <ul class="errorlist nonfield"><li>正しいEmailとパスワードを入力してください。どちらのフィールドも大文字と小文字は区
別されます。</li></ul>

    </td>
  </tr>


  <tr>
    <th><label for="id_username">Email:</label></th>
    <td>

      <input type="text" name="username" value="test" autofocus autocapitalize="none" autocomplete="username" maxlength="50" required id="id_username">


    </td>
  </tr>

  <tr>
    <th><label for="id_password">パスワード:</label></th>
    <td>

      <input type="password" name="password" autocomplete="current-password" required id="id_password">




    </td>
  </tr>
F
======================================================================
FAIL: test_success_post (accounts.tests.TestLoginView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\ttter\accounts\tests.py", line 210, in test_success_post
    self.assertRedirects(response_post, reverse('base:top'))
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\testcases.py", line 351, in assertRedirects
    self.assertEqual(
AssertionError: 200 != 302 : Response didn't redirect as expected: Response code was 200 (expected 302)

----------------------------------------------------------------------
Ran 14 tests in 1.144s

FAILED (failures=1)
Destroying test database for alias 'default'...
```
となってしまいます。
画面上でloginする際には問題ないのですが、User.objects.create_user()がうまくいってないのでしょうか？

**Comment by Akinori13** [comment]
inputのnameを確認しましょう。
パスワードはpasswordで問題ありませんが、E-mailはemailではありませんよね。POSTするデータを修正する必要があります。なおこれはaccounts.modelsのUSERNAME_FIELDと関連する問題です。

**Comment by YukiY727** [comment]
#4 いろいろ試してみたところ、動くようになったのですが、意図しない動き方をするようになってしまいました。
```
class TestLoginView(TestCase):

    def setUp(self):
        a = User.objects.create_user(
            username='test', email='test@ed.jp', password='t12e12s12t')
        print(a.get_username())
        self.url = reverse('accounts:login')

    def test_success_get(self):
        response_get = self.client.get(self.url)
        self.assertEqual(response_get.status_code, 200)
        self.assertTemplateUsed(response_get, 'accounts/login.html')

    def test_success_post(self):
        data = {
            'username': 'test@ed.jp',
            'password': 't12e12s12t'
        }
        response_post = self.client.post(self.url, data=data)
        self.assertRedirects(response_post, reverse('base:top'))
```
どこで間違えているかわからないです、、、

**Comment by Akinori13** [comment]
先ほどのコメントで述べた通り、USERNAME_FIELDに関連します。
POSTするdataのnameとvalueの組み合わせが意味を持ちます。
今回のログインフォームの必須の情報はEmailとPasswordです。しかしPOSTするnameはusernameとpasswordになります。

【動作しない】
```
data = {
            'email: 'test@ed.jp',
            'password': 't12e12s12t'
        }
```

【動作する】
```
data = {
            'username': 'test@ed.jp',
            'password': 't12e12s12t'
        }
```

**Comment by YukiY727** [comment]
なるほど、てっきりUSERNAME_FIELDは一意の識別を指定するものだとおもっていたのですが、中身のfieldも上書き(？)されてしまうのですね
すごくややこしいですが、なっとくできました！
ありがとうございます！
