### ISSUE TITLE
unfollowのtestでよくわからないエラーが返ってくる

### ISSUE THREAD

**Issue by YukiY727** [YukiY727/Twitter_clone#9]
#7 
のところで、python manage.py runserverではうまく動くようにできたのですが、
testを行うと、
```
Traceback (most recent call last):
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\ttter\accounts\tests.py", line 357, in test_success_post
    response = self.client.post(
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\client.py", line 756, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\client.py", line 407, in post
    return self.generic('POST', path, post_data, content_type,
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\client.py", line 473, in generic
    return self.request(**r)
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\client.py", line 721, in request
    self.check_exception(response)
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\client.py", line 582, in check_exception
    raise exc_value
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view accounts.views.view didn't return an HttpResponse object. It returned None instead.
```
というものがかえってきて、
```
ValueError: The view accounts.views.view didn't return an HttpResponse object. It returned None instead.
```
を調べても自分の中で何がだめなのかわからず困っています。
教えてもらえると嬉しいです！

**Comment by Akinori13** [comment]
翻訳すれば
```
ValueError: accounts.views.view は、HttpResponse オブジェクトを返しませんでした。代わりに None を返しました。
```

つまりUnFollowViewのPOST時にレスポンスが存在しないということです。レスポンスがなぜないのかUnFollowViewで検討しましたか？

実際にテストではなく手動で確認してみましょう！！！Pythonの文法も重ねて復習してみましょう（特にインデントとか）

**Comment by YukiY727** [comment]
解決しました
if文入らなかったときのこと考えてなかったです。ありがとうございます
